### PR TITLE
Add Turkish translation

### PR DESCRIPTION
**Pull request by berkaygunduzz**
I also want to translate help and about, how can i do?

### CODE REVIEW

**Comment by ashutoshgngwr** [comment]
Hi @berkaygunduzz!

Thank you for your contributions. I am still to review the PR but if you could enable "Allow edits from maintainers" option, I could push a commit containing necessary code to enable localization of those resources.

**Comment by berkaygunduzz** [comment]
Allow edits is already enabled for PR, is there another thing i should do?

**Comment by ashutoshgngwr** [comment]
@berkaygunduzz yeah, sorry mistake on my part.

**Comment by berkaygunduzz** [comment]
Do you want me to translate copyright?

**Comment by ashutoshgngwr** [comment]
@berkaygunduzz No. The copyright statement should remain as is.

**Comment by berkaygunduzz** [comment]
Done, is there anything else i can help?

**Review by ashutoshgngwr — APPROVED** [review]
LGTM! :+1: 

Great work! If you want, you could help in translating [Noice](https://github.com/ashutoshgngwr/noice) to Turkish.

**Comment by berkaygunduzz** [comment]
Sure, i will work on it

**Pull request merged**
